## actually spaced entries: 
# conf: width:820
# css: #inenrbox {margin: 0px 4px 4px 4px;} #entry: {margin: 10px;}

##closer entries:
#conf: 790
# css: #inenrbox {margin: 0px 4px 4px 4px;} #entry: {margin: 2px;}

# Window settings
width=790
height=600
location=center
show=dmenu
layer=overlay

# Layout
columns=3
image_size=250x141 # 16:9
allow_images=true
insensitive=true
hide_scroll=true
