preload = $HOME/dotfiles/wallpaper/theMage.jpg
preload = $HOME/dotfiles/wallhaven-yx6e9l.jpg
preload = $HOME/dotfiles/wallpaper/Hypr-chan.png
preload = $HOME/dotfiles/wallpaper/hyprforest.jpg

wallpaper = ,/home/DROS/dotfiles/wallpaper/theMage.jpg

