[mgr]
prepend_keymap = [

  # Recycle-bin
  { on = ["R","o"], run = "plugin recycle-bin -- open",           desc = "Open Trash" },
  { on = ["R","e"], run = "plugin recycle-bin -- empty",          desc = "Empty Trash" },
  { on = ["R","D"], run = "plugin recycle-bin -- emptyDays",      desc = "Empty by days deleted" },
  { on = ["R","r"], run = "plugin recycle-bin -- restore",        desc = "Restore from Trash" },
  
  # Compression
  { on = [ "c", "a", "a" ], run = "plugin compress",               desc = "Archive selected files" },
  { on = [ "c", "a", "p" ], run = "plugin compress -p",            desc = "Archive selected files (password)" },
  { on = [ "c", "a", "h" ], run = "plugin compress -ph",           desc = "Archive selected files (password+header)" },
  { on = [ "c", "a", "l" ], run = "plugin compress -l",            desc = "Archive selected files (compression level)" },
  { on = [ "c", "a", "u" ], run = "plugin compress -phl",          desc = "Archive selected files (password+header+level)" },

  # Clipboard
  { on  = ["y"],    run = [ "yank", 'plugin clipboard -- --action=copy' ] },
  { on  = ["x"],    run = [ "yank --cut", 'plugin clipboard -- --action=copy' ] },

  # Toggle Hidden
  { on = ".", run = [ "hidden toggle", "plugin pref-by-location -- save" ], desc = "Toggle the visibility of hidden files" },

  # Linemode
  { on = [ "m", "s" ], run = [ "linemode size", "plugin pref-by-location -- save" ],        desc = "Linemode: size" },
  { on = [ "m", "p" ], run = [ "linemode permissions", "plugin pref-by-location -- save" ], desc = "Linemode: permissions" },
  { on = [ "m", "b" ], run = [ "linemode btime", "plugin pref-by-location -- save" ],        desc = "Linemode: btime" },
  { on = [ "m", "m" ], run = [ "linemode mtime", "plugin pref-by-location -- save" ],        desc = "Linemode: mtime" },
  { on = [ "m", "o" ], run = [ "linemode owner", "plugin pref-by-location -- save" ],        desc = "Linemode: owner" },
  { on = [ "m", "n" ], run = [ "linemode none", "plugin pref-by-location -- save" ],         desc = "Linemode: none" },

  # Sorting
  { on = [ ",", "t" ], run = "plugin pref-by-location -- toggle",                                 desc = "Toggle auto-save preferences" },
  { on = [ ",", "d" ], run = "plugin pref-by-location -- disable",                                desc = "Disable auto-save preferences" },
  { on = [ ",", "R" ], run = [ "plugin pref-by-location -- reset" ],                              desc = "Reset preference of cwd" },
  { on = [ ",", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime", "plugin pref-by-location -- save" ], desc = "Sort by modified time" },
  { on = [ ",", "M" ], run = [ "sort mtime --reverse", "linemode mtime", "plugin pref-by-location -- save" ],    desc = "Sort by modified time (reverse)" },
  { on = [ ",", "b" ], run = [ "sort btime --reverse=no", "linemode btime", "plugin pref-by-location -- save" ], desc = "Sort by birth time" },
  { on = [ ",", "B" ], run = [ "sort btime --reverse", "linemode btime", "plugin pref-by-location -- save" ],    desc = "Sort by birth time (reverse)" },
  { on = [ ",", "e" ], run = [ "sort extension --reverse=no", "plugin pref-by-location -- save" ],               desc = "Sort by extension" },
  { on = [ ",", "E" ], run = [ "sort extension --reverse", "plugin pref-by-location -- save" ],                  desc = "Sort by extension (reverse)" },
  { on = [ ",", "a" ], run = [ "sort alphabetical --reverse=no", "plugin pref-by-location -- save" ],            desc = "Sort alphabetically" },
  { on = [ ",", "A" ], run = [ "sort alphabetical --reverse", "plugin pref-by-location -- save" ],               desc = "Sort alphabetically (reverse)" },
  { on = [ ",", "n" ], run = [ "sort natural --reverse=no", "plugin pref-by-location -- save" ],                 desc = "Sort naturally" },
  { on = [ ",", "N" ], run = [ "sort natural --reverse", "plugin pref-by-location -- save" ],                    desc = "Sort naturally (reverse)" },
  { on = [ ",", "s" ], run = [ "sort size --reverse=no", "linemode size", "plugin pref-by-location -- save" ],   desc = "Sort by size" },
  { on = [ ",", "S" ], run = [ "sort size --reverse", "linemode size", "plugin pref-by-location -- save" ],      desc = "Sort by size (reverse)" },
  { on = [ ",", "r" ], run = [ "sort random --reverse=no", "plugin pref-by-location -- save" ],                  desc = "Sort randomly" },

  # Closing current tab
  { on = "<C-x>", run = "close", desc = "Close the current tab, or quit if it's last" },

  # sudo nvim
  { on = [ "e" ], run = 'shell "sudo -E nvim \"$@\"" --block --confirm', desc = "Sudo nvim" },

  # gvfs (mount manager)
  { on = [ "M", "m" ], run = "plugin gvfs -- select-then-mount --jump", desc = "Select device to mount and jump to its mount point" },

    { on = [ "M", "j" ], run = "plugin gvfs --jump-to-device", desc = "jump to its mount point" },

  # This will remount device under current working directory (cwd)
  #   -> cwd = /run/user/1000/gvfs/DEVICE_1/FOLDER_A
  #   -> device mountpoint = /run/user/1000/gvfs/DEVICE_1
  #   -> remount this DEVIEC_1 if needed
  { on = [ "M", "R" ], run = "plugin gvfs -- remount-current-cwd-device", desc = "Remount device under cwd" },

  { on = [ "M", "u" ], run = "plugin gvfs -- select-then-unmount", desc = "Select device then unmount" },
  # Or this if you want to unmount and eject device.
  #   -> Ejected device can safely be removed.
  #   -> Ejecting a device will unmount all paritions/volumes under it.
  #   -> Fallback to normal unmount if not supported by device.
  { on = [ "M", "u" ], run = "plugin gvfs -- select-then-unmount --eject", desc = "Select device then eject" },

  # Also support force unmount/eject.
  #   -> Ignore outstanding file operations when unmounting or ejecting
  { on = [ "M", "U" ], run = "plugin gvfs -- select-then-unmount --eject --force", desc = "Select device then force to eject/unmount" },

  # Add Scheme/Mount URI:
  #   -> Available schemes: mtp, gphoto2, smb, sftp, ftp, nfs, dns-sd, dav, davs, dav+sd, davs+sd, afp, afc, sshfs
  #   -> Read more about the schemes here: https://wiki.gnome.org/Projects(2f)gvfs(2f)schemes.html
  #   -> Explain about the scheme:
  #       -> If it shows like this: {ftp,ftps,ftpis}://[user@]host[:port]
  #       -> All of the value within [] is optional. For values within {}, you must choose exactly one. All others are required.
  #       -> Example: {ftp,ftps,ftpis}://[user@]host[:port] => ip and port: "ftp://myusername@192.168.1.2:9999" or domain: "ftps://myusername@github.com"
  #       -> More examples: smb://user@192.168.1.2/share, smb://WORKGROUP;user@192.168.1.2/share, sftp://user@192.168.1.2/, ftp://192.168.1.2/
  # !WARNING: - Scheme/Mount URI shouldn't contain password.
  #           - Google Drive, One drive are listed automatically via GNOME Online Accounts (GOA). Avoid adding them.
  #           - MTP, GPhoto2, AFC, Hard disk/drive, fstab with x-gvfs-show are also listed automatically. Avoid adding them.
  #           - SSH, SFTP, FTP(s), AFC, DNS_SD now support [/share]. For example: sftp://user@192.168.1.2/home/user_name -> /share = /home/user_name
  #           - ssh:// is alias for sftp://.
  #             -> {sftp,ssh}://[user@]host[:port]. Host can be Host alias in .ssh/config file, ip or domain.
  #             -> For example (home is Host alias in .ssh/config file: Host home):
  #                  -> ssh://user_name@home/home/user_name -> this will mount root path, but jump to subfolder /home/user_name
  #                  -> sftp://user_name@192.168.1.2/home/user_name -> same as above but with ip
  #                  -> sftp://user_name@192.168.1.2:9999/home/user_name -> same as above but with ip and port
  { on = [ "M", "a" ], run = "plugin gvfs -- add-mount", desc = "Add a GVFS mount URI" },

  # Edit a Scheme/Mount URI
  #   -> Will clear saved passwords for that mount URI.
  { on = [ "M", "e" ], run = "plugin gvfs -- edit-mount", desc = "Edit a GVFS mount URI" },

  # Remove a Scheme/Mount URI
  #   -> Will clear saved passwords for that mount URI.
  { on = [ "M", "r" ], run = "plugin gvfs -- remove-mount", desc = "Remove a GVFS mount URI" },

  # Jump
  { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device", desc = "Select device then jump to its mount point" },
  # If you use `x-systemd.automount` in /etc/fstab or manually added automount unit,
  # then you can use `--automount` argument to auto mount device before jump.
  # Otherwise it won't show up in the jump list.
  { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device --automount", desc = "Automount then select device to jump to its mount point" },
  { on = [ "`", "`" ], run = "plugin gvfs -- jump-back-prev-cwd", desc = "Jump back to the position before jumped to device" },

  # Automount (This is different from `x-systemd.automount` in /etc/fstab)
  #   -> Hover over any file/folder under a mounted device then run `automount-when-cd` action to enable automount when cd/jump for that device.
  #   -> When you cd/jump to unmounted device mountpoint or its sub folder, this will auto-mount the device before jump.
  #   -> Works with any command or any bookmark plugin that change cwd. For example, use `yamb` to add bookmarks and jump to them, use yazi's built-in `cd` `back` `forward` commands:

  #   -> { on = [ "m", "a" ], run = [ "plugin yamb -- save", "plugin gvfs -- automount-when-cd" ], desc = "Add bookmark and enable automount when cd"}
  { on = [ "M", "t" ], run = "plugin gvfs -- automount-when-cd", desc = "Enable automount when cd to device under cwd" },
  { on = [ "M", "T" ], run = "plugin gvfs -- automount-when-cd --disabled", desc = "Disable automount when cd to device under cwd" },

  # Open with cmd
  { on = [ "o" ], run  = "plugin open-with-cmd", desc = "Open with command" }
]
