color0 #1a1111
color1 #ffb4ab
color2 #e2c28c
color3 #e7bdba
color4 #ffb3af
color5 #e2c28c
color6 #e7bdba
color7 #f1dedd
color8 #a08c8b
color9 #ffb4ab
color10 #e2c28c
color11 #e7bdba
color12 #ffb3af
color13 #e2c28c
color14 #e7bdba
color15 #f1dedd

cursor                #f1dedd
cursor_text_color     #1a1111
background            #1a1111
foreground            #f1dedd
selection_foreground  #d8c2c0
selection_background  #534342
url_color             #ffb3af
